headers:
  - Repository
  - Type
  - File Name
  - URL
  - Created On
  - Last Commit
  - Branch Protection
  - Required Checks Enforcement Level
  - Repo Archived
  - Analysis Result
assets:
  - type: Terraform
    file_match: '*.tf'
    matchType: file
    parse_function: terraform
  - type: Cloudformation (CFN)
    file_match: '*.yml'
    matchType: content
    content_match:
      - 'AWSTemplateFormatVersion:'
    parse_function: cloudformation
  - type: Cloudformation (CFN)
    file_match: '*.yaml'
    matchType: content
    content_match:
      - 'AWSTemplateFormatVersion:'
    parse_function: cloudformation
  - type: Python
    file_match: '*.py'
    matchType: content
    content_match:
      - 'import aws'
      - 'import aws-cdk'
      - 'import boto3'
    parse_function: boto3
  - type: PowerShell
    file_match: '*.ps1'
    matchType: content
    content_match:
      - Install-Module -Name AWSPowerShell
      - AWSPowerShell
    parse_function: powershell
  - type: Shell
    file_match: '*.sh'
    matchType: content
    content_match:
      - aws
    parse_function: shell
  - type: YAML (Ansible)
    file_match: '*.yml'
    matchType: content
    content_match:
      - 'name:'
      - 'amazon.aws.'
      - 'community.aws.'
    parse_function: ansible
  - type: YAML (Ansible)
    file_match: '*.yaml'
    matchType: content
    content_match:
      - 'name:'
      - 'amazon.aws.'
      - 'community.aws.'
    parse_function: ansible
  - type: JavaScript
    file_match: '*.js'
    matchType: content
    content_match:
      - 'aws-sdk'
      - 'import aws'
    parse_function: javascript # not ES5
  - type: TypeScript
    file_match: '*.ts'
    matchType: content
    content_match:
      - 'aws-sdk'
      - 'import aws'
    parse_function: javascript
  - type: Cloudformation (CFN)
    file_match: '*.json'
    matchType: content
    content_match:
      - 'AWSTemplateFormatVersion'
    parse_function: cloudformation
  - type: Ruby
    file_match: '*.rb'
    matchType: content
    content_match:
      - 'aws-sdk-'
    parse_function: ruby
  - type: Java
    file_match: '*.java'
    matchType: content
    content_match:
      - public class
      - 'import com.amazonaws.'
    parse_function: java
  - type: Chef
    file_match: '*.rb'
    matchType: content
    content_match:
      - 'aws_'
      - 'AwsCookbook'
    parse_function: chef
  - type: Jupyter Notebook
    file_match: '*.ipynb'
    matchType: content
    content_match:
      - 'import boto3'
      - 'import botocore'
      - 'import awscli'
    parse_function: jupyter
  - type: C#
    file_match: '*.cs'
    matchType: file
    content_match:
      - 'using Amazon.'
      - 'using AWS.'
    parse_function: csharp
  - type: .NET
    file_match: '*.cs'
    matchType: file
    content_match:
      - 'using Amazon.'
      - 'using AWS.'
    parse_function: csharp
  # - type: Chef
  #   file_match: '*.rb'
  #   matchType: content
  #   content_match:
  #     - 'AwsCookbook'
  # - type: C++
  #   file_match: '*.cpp'
  #   matchType: content
  #   content_match:
  #     - 'include <aws/core/Aws.h>'
  # - type: Jenkins
  #   file_match: '*.groovy'
  #   matchType: file
  # - type: Spring Cloud
  #   file_match: '*.java'
  #   matchType: content
  #   content_match:
  #     - package io.awspring.cloud
  #     - 'import org.springframework.cloud'
  #   parse_function: springcloud
  # - type: Dockerfile
  #   file_match: 'Dockerfile'
  #   matchType: content
  #   content_match:
  #     - FROM
  #     - RUN
  # - type: C#
  #   file_match: '*.cs'
  #   matchType: file
  # - type: C
  #   file_match: '*.c'
  #   matchType: file
  # - type: Makefile
  #   file_match: 'Makefile'
  #   matchType: file
#######
# - type: HTML
#   file_match: '*.html'
#   matchType: file
# - type: CI Configuration
#   file_match: .github/workflows/*.yml
#   matchType: content
#   content_match:
#     - actions/checkout
# - type: CSS
#   file_match: '*.css'
#   matchType: content
#   content_match:
#     - font-family:
#     - color:
# - type: XML/XSLT
#   file_match: '*.xml'
#   matchType: content
#   content_match:
#     - <?xml version=
#     - <xsl:stylesheet
# - type: SQL (T-SQL, PLSQL, HiveQL, PLpgSQL)
#   file_match: '*.sql'
#   matchType: content
#   content_match:
#     - SELECT
#     - CREATE TABLE
# - type: Apex
#   file_match: '*.cls'
#   matchType: file
# - type: Visual Basic .NET
#   file_match: '*.vb' # need to check the file content
#   matchType: file
# - type: VBA
#   file_match: '*.vba'
#   matchType: file
# - type: XSLT
#   file_match: '*.xslt'
#   matchType: file

# - type: ASP.NET
#   file_match: '*.aspx'
#   matchType: file
# - type: Batchfile
#   file_match: '*.bat'
#   matchType: file
# - type: COBOL
#   file_match: '*.cob'
#   matchType: file
# - type: Perl
#   file_match: '*.pl'
#   matchType: file
# - type: PLSQL
#   file_match: '*.sql'
#   matchType: file
# - type: R
#   file_match: '*.r'
#   matchType: file
# - type: Roff
#   file_match: '*.roff'
#   matchType: file
# - type: Scala
#   file_match: '*.scala'
#   matchType: file
# - type: Classic ASP
#   file_match: '*.asp'
#   matchType: file
# - type: Gherkin
#   file_match: '*.feature'
#   matchType: file
# - type: Objective-C
#   file_match: '*.m'
#   matchType: file
# - type: Rebol
#   file_match: '*.reb'
#   matchType: file
# - type: SCSS
#   file_match: '*.scss'
#   matchType: file
# - type: Swift
#   file_match: '*.swift'
#   matchType: file
# - type: Visual Basic
#   file_match: '*.vb'
#   matchType: file
# - type: Rich Text Format
#   file_match: '*.rtf'
#   matchType: file
# - type: HiveQL
#   file_match: '*.q'
#   matchType: file
# - type: Smatty
#   file_match: '*.sm'
#   matchType: file
# - type: IDL
#   file_match: '*.idl'
#   matchType: file
# - type: Raku
#   file_match: '*.raku'
#   matchType: file
# - type: TeX
#   file_match: '*.tex'
#   matchType: file
# - type: Tcl
#   file_match: '*.tcl'
#   matchType: file
# - type: PLpgSQL
#   file_match: '*.sql'
#   matchType: file
# - type: Matlab
#   file_match: '*.mat'
#   matchType: file
# - type: Jupyter Notebook
#   file_match: '*.ipynb'
#   matchType: file
