headers:
  - Repository
  - Type
  - File Name
  - URL
  - Created On
  - Last Commit
  - Branch Protection
  - Required Checks Enforcement Level
  - Repo Archived
  - Analysis Result
assets:
  - type: Terraform
    file_match: '*.tf'
    matchType: file
    parse_function: terraform
  - type: Cloudformation (CFN)
    file_match: '*.yml'
    matchType: content
    content_match:
      - 'AWSTemplateFormatVersion:'
    parse_function: cloudformation
  - type: Cloudformation (CFN)
    file_match: '*.yaml'
    matchType: content
    content_match:
      - 'AWSTemplateFormatVersion:'
    parse_function: cloudformation
  - type: Python
    file_match: '*.py'
    matchType: content
    content_match:
      - 'import aws'
      - 'import aws-cdk'
      - 'import boto3'
    parse_function: boto3
  - type: PowerShell
    file_match: '*.ps1'
    matchType: content
    content_match:
      - Install-Module -Name AWSPowerShell
      - AWSPowerShell
    parse_function: powershell
  - type: Shell
    file_match: '*.sh'
    matchType: content
    content_match:
      - aws
    parse_function: shell
  - type: YAML (Ansible)
    file_match: '*.yml'
    matchType: content
    content_match:
      - 'name:'
      - 'amazon.aws.'
      - 'community.aws.'
    parse_function: ansible
  - type: YAML (Ansible)
    file_match: '*.yaml'
    matchType: content
    content_match:
      - 'name:'
      - 'amazon.aws.'
      - 'community.aws.'
    parse_function: ansible
  - type: JavaScript
    file_match: '*.js'
    matchType: content
    content_match:
      - 'aws-sdk'
      - 'import aws'
    parse_function: javascript # not ES5
  - type: TypeScript
    file_match: '*.ts'
    matchType: content
    content_match:
      - 'aws-sdk'
      - 'import aws'
    parse_function: javascript
  - type: Cloudformation (CFN)
    file_match: '*.json'
    matchType: content
    content_match:
      - 'AWSTemplateFormatVersion'
    parse_function: cloudformation
  - type: Ruby
    file_match: '*.rb'
    matchType: content
    content_match:
      - 'aws-sdk-'
    parse_function: ruby
  - type: Java
    file_match: '*.java'
    matchType: content
    content_match:
      - public class
      - 'import com.amazonaws.'
    parse_function: java
  - type: Chef
    file_match: '*.rb'
    matchType: content
    content_match:
      - 'aws_'
      - 'AwsCookbook'
    parse_function: chef
  - type: Jupyter Notebook
    file_match: '*.ipynb'
    matchType: content
    content_match:
      - 'import boto3'
      - 'import botocore'
      - 'import awscli'
    parse_function: jupyter
  - type: SpringCloud
    file_match: '*.java'
    matchType: content
    content_match:
      - package io.awspring.cloud
      - 'import org.springframework.cloud'
    parse_function: springcloud
  - type: Manifest File
    file_match: '**/manifest.yml'
    matchType: file
    parse_function: manifest
  - type": Java Properties
    file_match: '**/*.properties'
    matchType: file
    parse_function: javaproperty
  - type: Jenkins
    file_match: '*.groovy'
    matchType: file
    parse_function: groovy 
  - type: Jenkins
    file_match: 'jenkinsfile'
    matchType: file
    parse_function: groovy
  - type: CSharp
    file_match: '*.cs'
    matchType: file
    content_match:
      - 'using System;'
      - 'using Amazon.'
      - 'using AWS.'
      - 'public class'
    parse_function: csharp
  - type: VBNet
    file_match: '*.vb'
    matchType: file
    content_match:
      - 'Imports System'
      - 'Imports Amazon.'
      - 'Imports AWS.'
      - 'Public Class'
    parse_function: dotnet
  - type: ASPNet
    file_match:
      - '*.aspx'
      - '*.ascx'
      - '*.asmx'
    matchType: file
    parse_function: dotnet
  - type: CSharpProject
    file_match: '*.csproj'
    matchType: file
    parse_function: dotnet
  - type: VBNetProject
    file_match: '*.vbproj'
    matchType: file
    parse_function: dotnet
